const bcrypt = require("bcryptjs");
const db = require("./database");
const postgres = require("./postgres-adapter");

const usePostgres = Boolean(process.env.DATABASE_URL);

function normalizeParentMobile(value) {
    if (value === null || value === undefined) return null;
    const cleaned = String(value).trim();
    if (!cleaned) return null;
    const digits = cleaned.replace(/[^0-9+]/g, "");
    if (!digits) return null;
    return digits.startsWith("+") ? digits : digits.replace(/^00/, "").replace(/^0+/, "");
}

function normalizeParentEmail(value) {
    if (value === null || value === undefined) return null;
    const cleaned = String(value).trim();
    return cleaned ? cleaned.toLowerCase() : null;
}

function normalizeRelationshipType(value) {
    const relationship = String(value || "Guardian").trim();
    const normalized = relationship.toLowerCase();
    if (["father", "dad", "male parent"].includes(normalized)) return "Father";
    if (["mother", "mom", "female parent"].includes(normalized)) return "Mother";
    return "Guardian";
}

function isPostgresConfigured() {
    return usePostgres;
}

async function ensurePostgresParentFamilyTables() {
    if (!usePostgres) return;
    await postgres.exec(`
        ALTER TABLE users ADD COLUMN IF NOT EXISTS management_role TEXT;
        CREATE TABLE IF NOT EXISTS parents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT,
            mobile TEXT UNIQUE,
            email TEXT UNIQUE,
            otp_verified BOOLEAN DEFAULT FALSE,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS parent_student_links (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
            student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
            relationship_type TEXT NOT NULL DEFAULT 'Guardian',
            is_primary BOOLEAN NOT NULL DEFAULT TRUE,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(parent_id, student_id)
        );
        CREATE TABLE IF NOT EXISTS parent_otp_verifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
            otp_hash TEXT NOT NULL,
            purpose TEXT NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0,
            used_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );
        ALTER TABLE parent_otp_verifications ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;
    `);
}

async function insertOrGetParentAsync({ fullName, mobile, email }) {
    if (!usePostgres) return insertOrGetParent({ fullName, mobile, email });

    const parentMobile = normalizeParentMobile(mobile);
    const parentEmail = normalizeParentEmail(email);
    if (!parentMobile && !parentEmail) return null;

    let parent = parentMobile
        ? await postgres.get("SELECT * FROM parents WHERE mobile = ?", [parentMobile])
        : null;
    if (!parent && parentEmail) {
        parent = await postgres.get("SELECT * FROM parents WHERE email = ?", [parentEmail]);
    }

    if (!parent) {
        parent = await postgres.get(`
            INSERT INTO parents (full_name, mobile, email, otp_verified, status)
            VALUES (?, ?, ?, FALSE, 'active')
            RETURNING *
        `, [fullName || null, parentMobile, parentEmail]);
    } else {
        parent = await postgres.get(`
            UPDATE parents
            SET full_name = COALESCE(?, full_name),
                mobile = COALESCE(?, mobile),
                email = COALESCE(?, email),
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            RETURNING *
        `, [fullName || null, parentMobile || parent.mobile, parentEmail || parent.email, parent.id]);
    }

    return parent;
}

async function ensureParentLinkAsync(parentId, studentId, relationshipType = "Guardian", isPrimary = 1) {
    if (!usePostgres) return ensureParentLink(parentId, studentId, relationshipType, isPrimary);
    return postgres.get(`
        INSERT INTO parent_student_links (parent_id, student_id, relationship_type, is_primary, status)
        VALUES (?, ?, ?, ?, 'active')
        ON CONFLICT (parent_id, student_id) DO UPDATE SET
            relationship_type = EXCLUDED.relationship_type,
            is_primary = EXCLUDED.is_primary,
            status = 'active',
            updated_at = CURRENT_TIMESTAMP
        RETURNING *
    `, [parentId, studentId, normalizeRelationshipType(relationshipType), Number(isPrimary) ? true : false]);
}

async function getParentByMobileOrEmailAsync(mobile, email) {
    if (!usePostgres) return getParentByMobileOrEmail(mobile, email);
    const normalizedMobile = normalizeParentMobile(mobile);
    const normalizedEmail = normalizeParentEmail(email);
    let parent = normalizedMobile
        ? await postgres.get("SELECT * FROM parents WHERE mobile = ?", [normalizedMobile])
        : null;
    if (!parent && normalizedEmail) {
        parent = await postgres.get("SELECT * FROM parents WHERE email = ?", [normalizedEmail]);
    }
    return parent || null;
}

async function updateParentMobileAsync(parentId, mobile) {
    const normalizedMobile = normalizeParentMobile(mobile);
    if (!normalizedMobile) return null;
    if (!usePostgres) {
        db.prepare(`
            UPDATE parents SET mobile = ?, otp_verified = 1, updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
        `).run(normalizedMobile, parentId);
        return db.prepare("SELECT * FROM parents WHERE id = ?").get(parentId);
    }
    return postgres.get(`
        UPDATE parents
        SET mobile = ?, otp_verified = TRUE, updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        RETURNING *
    `, [normalizedMobile, parentId]);
}

async function createParentOtpRecordAsync(parentId, purpose = "login", expiryMinutes = 10) {
    if (!usePostgres) return createParentOtpRecord(parentId, purpose, expiryMinutes);
    const otp = String(Math.floor(100000 + Math.random() * 900000));
    const otpHash = await bcrypt.hash(otp, 10);
    const expiresAt = new Date(Date.now() + expiryMinutes * 60 * 1000).toISOString();
    await postgres.run(`
        INSERT INTO parent_otp_verifications (parent_id, otp_hash, purpose, expires_at)
        VALUES (?, ?, ?, ?)
    `, [parentId, otpHash, purpose, expiresAt]);
    return { otp, otpHash, expiresAt };
}

async function verifyParentOtpAsync(parentId, otp, purpose) {
    if (!usePostgres) return verifyParentOtp(parentId, otp, purpose);
    const record = await postgres.get(`
        SELECT * FROM parent_otp_verifications
        WHERE parent_id = ? AND purpose = ? AND used_at IS NULL
        ORDER BY id DESC LIMIT 1
    `, [parentId, purpose]);
    if (!record) return { valid: false, reason: "no_active_otp" };

    const attempts = Number(record.attempts || 0);
    if (attempts >= 5) {
        await postgres.run("UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [record.id]);
        return { valid: false, reason: "attempt_limit" };
    }
    if (new Date(record.expires_at).getTime() < Date.now()) {
        await postgres.run("UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [record.id]);
        return { valid: false, reason: "expired_otp" };
    }
    if (!(await bcrypt.compare(String(otp || "").trim(), record.otp_hash))) {
        await postgres.run("UPDATE parent_otp_verifications SET attempts = COALESCE(attempts, 0) + 1 WHERE id = ?", [record.id]);
        return { valid: false, reason: "invalid_otp" };
    }
    await postgres.transaction(async transaction => {
        await transaction.run("UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?", [record.id]);
        await transaction.run("UPDATE parents SET otp_verified = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = ?", [parentId]);
    });
    return { valid: true, reason: "ok" };
}

async function getLinkedStudentsForParentAsync(parentId) {
    if (!usePostgres) return getLinkedStudentsForParent(parentId);
    return postgres.all(`
        SELECT s.* FROM parent_student_links l
        JOIN students s ON s.id = l.student_id
        WHERE l.parent_id = ? AND l.status = 'active'
        ORDER BY s.full_name ASC
    `, [parentId]);
}

async function isStudentLinkedToParentAsync(parentId, studentId) {
    if (!usePostgres) return isStudentLinkedToParent(parentId, studentId);
    return Boolean(await postgres.get(`
        SELECT 1 FROM parent_student_links
        WHERE parent_id = ? AND student_id = ? AND status = 'active' LIMIT 1
    `, [parentId, studentId]));
}

async function getLinkedStudentByIdAsync(parentId, studentId) {
    if (!usePostgres) {
        return db.prepare(`
            SELECT s.* FROM parent_student_links l
            JOIN students s ON s.id = l.student_id
            WHERE l.parent_id = ? AND l.student_id = ? AND l.status = 'active'
            LIMIT 1
        `).get(parentId, studentId);
    }
    return postgres.get(`
        SELECT s.* FROM parent_student_links l
        JOIN students s ON s.id = l.student_id
        WHERE l.parent_id = ? AND l.student_id = ? AND l.status = 'active'
        LIMIT 1
    `, [parentId, studentId]);
}

async function getParentDashboardDataAsync(parentId, studentId) {
    if (!usePostgres) return null;
    const student = await getLinkedStudentByIdAsync(parentId, studentId);
    if (!student) return null;
    const [feeSummary, attendance, marks, notifications, children] = await Promise.all([
        postgres.get(`
            SELECT COALESCE(SUM(total_amount), 0) AS total_amount,
                   COALESCE(SUM(paid_amount), 0) AS paid_amount,
                   COALESCE(SUM(pending_amount), 0) AS pending_amount,
                   COUNT(*) AS records
            FROM fees WHERE student_id = ?
        `, [student.id]),
        postgres.all(`
            SELECT id, student_id, subject AS subject_name, subject AS subject_code,
                   attendance_date, status
            FROM attendance WHERE student_id = ?
            ORDER BY attendance_date DESC LIMIT 20
        `, [student.id]),
        postgres.all(`
            SELECT m.id, m.student_id, m.subject_id, m.exam_type,
                   m.marks AS total_marks, m.max_marks,
                   COALESCE(s.name, 'Subject ' || m.subject_id) AS subject_name,
                   COALESCE(s.code, 'SUBJ') AS subject_code,
                   COALESCE(m.exam_date, '') AS created_at
            FROM marks m LEFT JOIN subjects s ON s.id = m.subject_id
            WHERE m.student_id = ?
            ORDER BY COALESCE(m.exam_date, '') DESC, m.id DESC LIMIT 20
        `, [student.id]),
        postgres.all(`
            SELECT * FROM notifications
            WHERE audience IN ('All', 'Parents')
            ORDER BY created_at DESC LIMIT 20
        `),
        getLinkedStudentsForParentAsync(parentId)
    ]);
    return { student, feeSummary, attendance, marks, notifications, children };
}

async function getParentProfileDataAsync(parentId, studentId) {
    if (!usePostgres) return null;
    const student = await getLinkedStudentByIdAsync(parentId, studentId);
    if (!student) return null;
    const [attendance, marks, fees, notifications] = await Promise.all([
        postgres.all(`
            SELECT id, student_id, subject AS subject_name, subject AS subject_code,
                   attendance_date, status
            FROM attendance WHERE student_id = ?
            ORDER BY attendance_date DESC LIMIT 30
        `, [student.id]),
        postgres.all(`
            SELECT m.id, m.student_id, m.subject_id, m.exam_type,
                   m.marks AS total_marks, m.max_marks,
                   COALESCE(s.name, 'Subject ' || m.subject_id) AS subject_name,
                   COALESCE(s.code, 'SUBJ') AS subject_code,
                   COALESCE(m.exam_date, '') AS created_at
            FROM marks m LEFT JOIN subjects s ON s.id = m.subject_id
            WHERE m.student_id = ?
            ORDER BY COALESCE(m.exam_date, '') DESC, m.id DESC LIMIT 30
        `, [student.id]),
        postgres.all("SELECT * FROM fees WHERE student_id = ? ORDER BY academic_year DESC, fee_year DESC", [student.id]),
        postgres.all("SELECT * FROM notifications WHERE audience IN ('All', 'Parents') ORDER BY created_at DESC LIMIT 20")
    ]);
    return { student, attendance, marks, fees, notifications };
}

function ensureParentFamilyTables() {
    db.exec(`
        CREATE TABLE IF NOT EXISTS roles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            description TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS permissions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            permission_key TEXT UNIQUE NOT NULL,
            description TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS role_permissions (
            role_id INTEGER NOT NULL,
            permission_key TEXT NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (role_id, permission_key),
            FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS user_roles (
            user_id INTEGER NOT NULL,
            role_id INTEGER NOT NULL,
            is_primary INTEGER DEFAULT 1,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, role_id),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS user_role_scopes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            role_id INTEGER NOT NULL,
            scope TEXT NOT NULL,
            department_id INTEGER,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, role_id, department_id),
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS parents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            full_name TEXT,
            mobile TEXT UNIQUE,
            email TEXT UNIQUE,
            otp_verified INTEGER DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'inactive', 'pending', 'blocked')),
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS parent_student_links (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            parent_id INTEGER NOT NULL,
            student_id INTEGER NOT NULL,
            relationship_type TEXT NOT NULL DEFAULT 'Guardian' CHECK(relationship_type IN ('Father', 'Mother', 'Guardian')),
            is_primary INTEGER NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'inactive', 'blocked')),
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(parent_id, student_id),
            FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE CASCADE,
            FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS parent_otp_verifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            parent_id INTEGER NOT NULL,
            otp_hash TEXT NOT NULL,
            purpose TEXT NOT NULL CHECK(purpose IN ('registration verification', 'login', 'mobile change')),
            expires_at DATETIME NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0,
            used_at DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE CASCADE
        );
    `);

    const otpColumns = new Set(db.prepare(`PRAGMA table_info(parent_otp_verifications)`).all().map((column) => column.name));
    if (!otpColumns.has("attempts")) {
        db.exec(`ALTER TABLE parent_otp_verifications ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0`);
    }

    db.exec(`
        CREATE UNIQUE INDEX IF NOT EXISTS idx_parents_mobile_unique ON parents(mobile) WHERE mobile IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS idx_parents_email_unique ON parents(email) WHERE email IS NOT NULL;
        CREATE INDEX IF NOT EXISTS idx_parent_student_links_parent ON parent_student_links(parent_id);
        CREATE INDEX IF NOT EXISTS idx_parent_student_links_student ON parent_student_links(student_id);
        CREATE INDEX IF NOT EXISTS idx_parent_otp_parent ON parent_otp_verifications(parent_id, purpose, expires_at);
    `);

    const defaultRoles = [
        ["student", "Default student role"],
        ["parent", "Parent role with student-linked access"],
        ["faculty", "Faculty role"],
        ["admin", "Administrative role"],
        ["superadmin", "Super administrator role"]
    ];

    const defaultPermissions = [
        ["student.self.read", "Read own student profile"],
        ["parent.linked_student.read", "Read linked student data"],
        ["parent.linked_student.update", "Update linked student data"],
        ["faculty.department.read", "Read department data"],
        ["admin.college.write", "Write college-level data"]
    ];

    const insertRole = db.prepare(`INSERT OR IGNORE INTO roles (name, description) VALUES (?, ?)`);
    const insertPermission = db.prepare(`INSERT OR IGNORE INTO permissions (permission_key, description) VALUES (?, ?)`);

    defaultRoles.forEach(([name, description]) => insertRole.run(name, description));
    defaultPermissions.forEach(([key, description]) => insertPermission.run(key, description));

    const parentRoleId = db.prepare(`SELECT id FROM roles WHERE name = 'parent'`).get()?.id;
    if (parentRoleId) {
        const permissionKeys = ["parent.linked_student.read", "parent.linked_student.update"];
        permissionKeys.forEach((permissionKey) => {
            const permissionId = db.prepare(`SELECT id FROM permissions WHERE permission_key = ?`).get(permissionKey)?.id;
            if (permissionId) {
                db.prepare(`INSERT OR IGNORE INTO role_permissions (role_id, permission_key) VALUES (?, ?)`)
                    .run(parentRoleId, permissionKey);
            }
        });
    }
}

function getLegacyParentRecords() {
    return db.prepare(`
        SELECT id, parent_name, parent_mobile, parent_email
        FROM students
        WHERE (
            TRIM(COALESCE(parent_name, '')) <> '' OR
            TRIM(COALESCE(parent_mobile, '')) <> '' OR
            TRIM(COALESCE(parent_email, '')) <> ''
        )
    `).all();
}

function insertOrGetParent({ fullName, mobile, email }) {
    const parentMobile = normalizeParentMobile(mobile);
    const parentEmail = normalizeParentEmail(email);

    if (!parentMobile && !parentEmail) {
        return null;
    }

    let parent = null;
    if (parentMobile) {
        parent = db.prepare(`SELECT * FROM parents WHERE mobile = ?`).get(parentMobile);
    }

    if (!parent && parentEmail) {
        parent = db.prepare(`SELECT * FROM parents WHERE email = ?`).get(parentEmail);
    }

    if (!parent) {
        const result = db.prepare(`
            INSERT INTO parents (full_name, mobile, email, otp_verified, status, created_at, updated_at)
            VALUES (?, ?, ?, 0, 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        `).run(
            fullName || null,
            parentMobile || null,
            parentEmail || null
        );

        parent = db.prepare(`SELECT * FROM parents WHERE id = ?`).get(result.lastInsertRowid);
    } else {
        const existingName = parent.full_name || fullName || null;
        db.prepare(`
            UPDATE parents
            SET full_name = COALESCE(?, full_name),
                mobile = COALESCE(?, mobile),
                email = COALESCE(?, email),
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
        `).run(existingName || null, parentMobile || parent.mobile || null, parentEmail || parent.email || null, parent.id);
        parent = db.prepare(`SELECT * FROM parents WHERE id = ?`).get(parent.id);
    }

    return parent;
}

function ensureParentLink(parentId, studentId, relationshipType = "Guardian", isPrimary = 1) {
    if (!parentId || !studentId) return null;

    const normalizedRelationship = normalizeRelationshipType(relationshipType);
    const existing = db.prepare(`
        SELECT * FROM parent_student_links
        WHERE parent_id = ? AND student_id = ?
    `).get(parentId, studentId);

    if (existing) {
        db.prepare(`
            UPDATE parent_student_links
            SET relationship_type = ?, is_primary = ?, status = 'active', updated_at = CURRENT_TIMESTAMP
            WHERE parent_id = ? AND student_id = ?
        `).run(normalizedRelationship, Number(isPrimary) ? 1 : 0, parentId, studentId);
        return db.prepare(`SELECT * FROM parent_student_links WHERE parent_id = ? AND student_id = ?`).get(parentId, studentId);
    }

    const result = db.prepare(`
        INSERT INTO parent_student_links (parent_id, student_id, relationship_type, is_primary, status, created_at, updated_at)
        VALUES (?, ?, ?, ?, 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    `).run(parentId, studentId, normalizedRelationship, Number(isPrimary) ? 1 : 0);

    return db.prepare(`SELECT * FROM parent_student_links WHERE id = ?`).get(result.lastInsertRowid);
}

function migrateLegacyParentData() {
    const students = getLegacyParentRecords();

    students.forEach((student) => {
        const parent = insertOrGetParent({
            fullName: student.parent_name,
            mobile: student.parent_mobile,
            email: student.parent_email
        });

        if (!parent || !student.id) return;
        ensureParentLink(parent.id, student.id, "Guardian", 1);
    });
}

async function createParentOtpRecord(parentId, purpose = "login", expiryMinutes = 10) {
    const otp = String(Math.floor(100000 + Math.random() * 900000));
    const otpHash = await bcrypt.hash(otp, 10);
    const expiresAt = new Date(Date.now() + expiryMinutes * 60 * 1000).toISOString();

    db.prepare(`
        INSERT INTO parent_otp_verifications (parent_id, otp_hash, purpose, expires_at, created_at)
        VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
    `).run(parentId, otpHash, purpose, expiresAt);

    return { otp, otpHash, expiresAt };
}

async function verifyParentOtp(parentId, otp, purpose) {
    const record = db.prepare(`
        SELECT *
        FROM parent_otp_verifications
        WHERE parent_id = ? AND purpose = ? AND used_at IS NULL
        ORDER BY id DESC
        LIMIT 1
    `).get(parentId, purpose);

    if (!record) {
        return { valid: false, reason: "no_active_otp" };
    }

    if (Number(record.attempts || 0) >= 5) {
        db.prepare(`UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?`).run(record.id);
        return { valid: false, reason: "attempt_limit" };
    }

    const now = Date.now();
    const expiresAt = new Date(record.expires_at).getTime();

    if (expiresAt < now) {
        db.prepare(`UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?`).run(record.id);
        return { valid: false, reason: "expired_otp" };
    }

    const isMatch = await bcrypt.compare(String(otp || "").trim(), record.otp_hash);
    if (!isMatch) {
        db.prepare(`UPDATE parent_otp_verifications SET attempts = attempts + 1 WHERE id = ?`).run(record.id);
        return { valid: false, reason: "invalid_otp" };
    }

    db.prepare(`UPDATE parent_otp_verifications SET used_at = CURRENT_TIMESTAMP WHERE id = ?`).run(record.id);
    db.prepare(`UPDATE parents SET otp_verified = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?`).run(parentId);
    return { valid: true, reason: "ok" };
}

function getParentByMobileOrEmail(mobile, email) {
    const normalizedMobile = normalizeParentMobile(mobile);
    const normalizedEmail = normalizeParentEmail(email);

    if (normalizedMobile) {
        const parent = db.prepare(`SELECT * FROM parents WHERE mobile = ?`).get(normalizedMobile);
        if (parent) return parent;
    }

    if (normalizedEmail) {
        return db.prepare(`SELECT * FROM parents WHERE email = ?`).get(normalizedEmail);
    }

    return null;
}

function getLinkedStudentsForParent(parentId) {
    return db.prepare(`
        SELECT s.*
        FROM parent_student_links l
        JOIN students s ON s.id = l.student_id
        WHERE l.parent_id = ? AND l.status = 'active' AND s.id IS NOT NULL
        ORDER BY s.full_name ASC
    `).all(parentId);
}

function isStudentLinkedToParent(parentId, studentId) {
    const row = db.prepare(`
        SELECT 1
        FROM parent_student_links
        WHERE parent_id = ? AND student_id = ? AND status = 'active'
        LIMIT 1
    `).get(parentId, studentId);

    return Boolean(row);
}

module.exports = {
    isPostgresConfigured,
    ensurePostgresParentFamilyTables,
    insertOrGetParentAsync,
    ensureParentLinkAsync,
    getParentByMobileOrEmailAsync,
    updateParentMobileAsync,
    createParentOtpRecordAsync,
    verifyParentOtpAsync,
    getLinkedStudentsForParentAsync,
    isStudentLinkedToParentAsync,
    getLinkedStudentByIdAsync,
    getParentDashboardDataAsync,
    getParentProfileDataAsync,
    ensureParentFamilyTables,
    migrateLegacyParentData,
    createParentOtpRecord,
    verifyParentOtp,
    getParentByMobileOrEmail,
    getLinkedStudentsForParent,
    isStudentLinkedToParent,
    insertOrGetParent,
    ensureParentLink,
    normalizeParentMobile,
    normalizeParentEmail,
    normalizeRelationshipType
};
