-- KHIT Family PostgreSQL staging schema for the planned SQLite migration.
--
-- This file is intentionally non-destructive: it contains no DROP, TRUNCATE,
-- DELETE, or ALTER TABLE statements. It has not been executed against any
-- PostgreSQL database. Source SQLite IDs may be inserted explicitly because
-- identity columns use GENERATED BY DEFAULT AS IDENTITY.
--
-- The nullable legacy/canonical columns preserve the live SQLite catalog. They
-- must be reconciled and validated before a later migration adds stricter
-- constraints or changes the application runtime.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL,
    management_role TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_key TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_key)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    is_primary BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT,
    mobile TEXT UNIQUE,
    email TEXT UNIQUE,
    otp_verified BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parent_otp_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    otp_hash TEXT NOT NULL,
    purpose TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users(id),
    student_id TEXT NOT NULL UNIQUE,
    roll_number TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT,
    mobile TEXT,
    department TEXT,
    year INTEGER,
    section TEXT,
    academic_year TEXT,
    fee_category TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    dob TEXT,
    gender TEXT,
    parent_name TEXT,
    parent_mobile TEXT,
    parent_email TEXT,
    address TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    pincode TEXT,
    profile_photo TEXT,
    linkedin_url TEXT,
    github_url TEXT,
    portfolio_url TEXT,
    instagram_url TEXT,
    other_link_url TEXT
);

CREATE TABLE IF NOT EXISTS parent_student_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL DEFAULT 'Guardian',
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (parent_id, student_id)
);

CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE REFERENCES users(id),
    faculty_id TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT,
    mobile TEXT,
    department TEXT,
    designation TEXT,
    qualification TEXT,
    specialization TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT,
    hod_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS user_role_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    scope TEXT NOT NULL,
    department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role_id, department_id)
);

CREATE TABLE IF NOT EXISTS user_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    department_id BIGINT NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
    designation TEXT NOT NULL DEFAULT 'Faculty',
    role_name TEXT NOT NULL DEFAULT 'faculty',
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    from_date TEXT,
    to_date TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, department_id, role_name)
);

CREATE TABLE IF NOT EXISTS academic_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE,
    label TEXT,
    starts_on TEXT,
    ends_on TEXT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT,
    department TEXT,
    year INTEGER,
    semester INTEGER,
    section TEXT
);

CREATE TABLE IF NOT EXISTS fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    academic_year TEXT NOT NULL,
    fee_year INTEGER NOT NULL,
    total_amount NUMERIC(12,2) DEFAULT 0,
    paid_amount NUMERIC(12,2) DEFAULT 0,
    pending_amount NUMERIC(12,2) DEFAULT 0,
    status TEXT DEFAULT 'Pending'
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    subject TEXT NOT NULL,
    attendance_date DATE NOT NULL,
    status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE SET NULL,
    exam_type TEXT,
    marks NUMERIC(8,2) DEFAULT 0,
    max_marks NUMERIC(8,2) DEFAULT 100,
    exam_date TEXT
);

CREATE TABLE IF NOT EXISTS result_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    department TEXT,
    year INTEGER,
    semester INTEGER,
    section TEXT,
    academic_year TEXT,
    subject TEXT,
    subject_code TEXT,
    internal_marks NUMERIC(8,2) DEFAULT 0,
    external_marks NUMERIC(8,2) DEFAULT 0,
    total_marks NUMERIC(8,2) DEFAULT 0,
    grade TEXT,
    grade_point NUMERIC(4,2) DEFAULT 0,
    pass_status TEXT DEFAULT 'Pending',
    backlog_status TEXT DEFAULT 'None',
    sgpa NUMERIC(4,2) DEFAULT 0,
    cgpa NUMERIC(4,2) DEFAULT 0,
    result_status TEXT DEFAULT 'Uploaded',
    publication_status TEXT DEFAULT 'Draft',
    reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    published_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    published_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT,
    audience TEXT DEFAULT 'All',
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    branch TEXT,
    year INTEGER,
    section TEXT
);

CREATE TABLE IF NOT EXISTS notification_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    read_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (notification_id, student_id)
);

CREATE TABLE IF NOT EXISTS notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    UNIQUE (notification_id, student_id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    event_date TEXT,
    event_time TEXT,
    venue TEXT,
    category TEXT,
    image_url TEXT,
    audience TEXT DEFAULT 'All',
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    audience TEXT DEFAULT 'All Students',
    image_url TEXT,
    document_url TEXT,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    category TEXT,
    media_path TEXT,
    link_url TEXT,
    published_at TIMESTAMPTZ,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    document_name TEXT NOT NULL,
    document_type TEXT,
    file_url TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    student_id BIGINT,
    title TEXT,
    category TEXT,
    file_path TEXT,
    uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    visibility TEXT DEFAULT 'Private',
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    entity_type TEXT,
    entity_id BIGINT,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS password_reset_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    otp_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    description TEXT,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fee_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    amount NUMERIC(12,2) NOT NULL,
    payment_mode TEXT,
    transaction_id TEXT UNIQUE,
    payment_reference TEXT,
    payment_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fee_id BIGINT,
    method TEXT,
    receipt_path TEXT,
    paid_at TIMESTAMPTZ,
    status TEXT DEFAULT 'Paid'
);

-- fee_id is intentionally nullable and unconstrained until each payment can
-- be matched to a fee; the live SQLite table does not contain fee_id.
CREATE TABLE IF NOT EXISTS fee_reimbursement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    status TEXT DEFAULT 'Pending',
    amount NUMERIC(12,2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    academic_year TEXT,
    reference_number TEXT,
    remarks TEXT
);

CREATE TABLE IF NOT EXISTS buses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number TEXT NOT NULL UNIQUE,
    route_name TEXT,
    status TEXT DEFAULT 'Active',
    route TEXT,
    available BOOLEAN DEFAULT TRUE,
    driver_name TEXT,
    driver_mobile TEXT,
    bus_fee NUMERIC(12,2),
    academic_year TEXT
);

CREATE TABLE IF NOT EXISTS bus_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_id BIGINT NOT NULL REFERENCES buses(id) ON DELETE CASCADE,
    stop_name TEXT NOT NULL,
    pickup_time TEXT,
    arrival_time TEXT,
    sequence_number INTEGER
);

CREATE TABLE IF NOT EXISTS student_bus_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    bus_id BIGINT NOT NULL REFERENCES buses(id) ON DELETE CASCADE,
    stop_id BIGINT REFERENCES bus_stops(id) ON DELETE SET NULL,
    academic_year TEXT,
    payment_status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ,
    UNIQUE (student_id, academic_year)
);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id BIGINT REFERENCES faculty(id) ON DELETE SET NULL,
    subject_id BIGINT REFERENCES subjects(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    due_date TEXT,
    attachment_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deadline TEXT,
    attachment_path TEXT,
    assigned_by BIGINT
);

CREATE TABLE IF NOT EXISTS assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    file_url TEXT,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    marks NUMERIC(8,2),
    remarks TEXT,
    status TEXT NOT NULL DEFAULT 'Pending',
    UNIQUE (assignment_id, student_id)
);

CREATE TABLE IF NOT EXISTS study_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    material_type TEXT NOT NULL DEFAULT 'Document',
    file_url TEXT,
    subject TEXT,
    department TEXT,
    year INTEGER,
    section TEXT,
    uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    faculty_id BIGINT REFERENCES faculty(id) ON DELETE SET NULL,
    from_date TEXT NOT NULL,
    to_date TEXT NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'Pending',
    response TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    starts_on TEXT,
    ends_on TEXT,
    reviewer_remarks TEXT,
    reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS placement_drives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    job_role TEXT,
    description TEXT,
    eligibility TEXT,
    drive_date TEXT,
    location TEXT,
    package TEXT,
    application_deadline TEXT,
    status TEXT DEFAULT 'Open',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    company TEXT,
    package_details TEXT
);

CREATE TABLE IF NOT EXISTS placement_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_id BIGINT NOT NULL REFERENCES placement_drives(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Applied',
    applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (drive_id, student_id)
);

CREATE TABLE IF NOT EXISTS internships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    role TEXT,
    description TEXT,
    eligibility TEXT,
    start_date TEXT,
    end_date TEXT,
    application_deadline TEXT,
    status TEXT DEFAULT 'Open',
    company TEXT,
    duration TEXT,
    location TEXT,
    stipend TEXT,
    deadline TEXT,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    achievement_date DATE,
    category TEXT,
    evidence_path TEXT,
    visibility TEXT DEFAULT 'Private',
    created_at TIMESTAMPTZ
);

-- The live SQLite catalog did not expose FKs/checks for this legacy table.
-- Validate ownership before adding the planned exactly-one-owner constraint.
CREATE TABLE IF NOT EXISTS profile_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT,
    faculty_id BIGINT,
    platform TEXT NOT NULL,
    url TEXT NOT NULL,
    visibility TEXT DEFAULT 'Private',
    created_at TIMESTAMPTZ
);

-- The live timetable is denormalized. Normalized ID columns are optional until
-- a later, explicit department/subject/faculty mapping is approved.
CREATE TABLE IF NOT EXISTS timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department TEXT,
    year INTEGER,
    section TEXT,
    day TEXT,
    period INTEGER,
    subject TEXT,
    faculty_name TEXT,
    room TEXT,
    start_time TEXT,
    end_time TEXT,
    department_id BIGINT,
    subject_id BIGINT,
    faculty_id BIGINT,
    weekday TEXT,
    starts_at TEXT,
    ends_at TEXT,
    academic_year TEXT
);

CREATE TABLE IF NOT EXISTS gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    category TEXT,
    event_date TEXT,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    audience TEXT DEFAULT 'College Members',
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    video_url TEXT NOT NULL,
    thumbnail_url TEXT,
    category TEXT,
    audience TEXT DEFAULT 'All',
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    thumbnail_path TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- Indexes equivalent to the live SQLite indexes, with additional indexes for
-- relationships used by the planned load and later application queries.
CREATE INDEX IF NOT EXISTS idx_students_department_year ON students(department, year);
CREATE INDEX IF NOT EXISTS idx_users_username_role ON users(username, role);
CREATE INDEX IF NOT EXISTS idx_students_user_id ON students(user_id);
CREATE INDEX IF NOT EXISTS idx_students_student_id_roll ON students(student_id, roll_number);
CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON attendance(student_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_student_subject ON attendance(student_id, subject);
CREATE INDEX IF NOT EXISTS idx_marks_student ON marks(student_id);
CREATE INDEX IF NOT EXISTS idx_marks_student_subject_date ON marks(student_id, subject_id, exam_date);
CREATE INDEX IF NOT EXISTS idx_result_records_student ON result_records(student_id);
CREATE INDEX IF NOT EXISTS idx_result_records_department ON result_records(department);
CREATE INDEX IF NOT EXISTS idx_result_records_academic_year ON result_records(academic_year);
CREATE INDEX IF NOT EXISTS idx_result_records_semester ON result_records(semester);
CREATE INDEX IF NOT EXISTS idx_result_records_section ON result_records(section);
CREATE INDEX IF NOT EXISTS idx_result_records_publication ON result_records(publication_status);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_audience_created_at ON notifications(audience, created_at);
CREATE INDEX IF NOT EXISTS idx_notification_reads_student ON notification_reads(student_id, notification_id);
CREATE INDEX IF NOT EXISTS idx_fees_student_year_status ON fees(student_id, academic_year, status);
CREATE INDEX IF NOT EXISTS idx_faculty_department ON faculty(department);
CREATE INDEX IF NOT EXISTS idx_assignments_subject_deadline ON assignments(subject_id, deadline);
CREATE INDEX IF NOT EXISTS idx_assignment_submissions_student ON assignment_submissions(student_id, assignment_id);
CREATE INDEX IF NOT EXISTS idx_documents_student_visibility_created ON documents(student_id, visibility, created_at);
CREATE INDEX IF NOT EXISTS idx_leave_student_status_created ON leave_requests(student_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_bus_assignments_student_year ON student_bus_assignments(student_id, academic_year);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_study_materials_target ON study_materials(department, year, section);
CREATE INDEX IF NOT EXISTS idx_fee_payments_student ON fee_payments(student_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_placement_applications_student ON placement_applications(student_id);